name: Menuconfig

on:
  workflow_dispatch:

jobs:
  menuconfig:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 防止会话过早终止

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
          rsync unzip zlib1g-dev

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall.git;packages" >> feeds.conf.default
        echo "src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Start tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Keep session alive
      run: sleep 6h
